### ISSUE TITLE
Krippendorff's alpha returns 0 when there's only one disagreement

### ISSUE THREAD

**Issue by imranraad07** [o-P-o/disagree#7]
For a dataset like this:

```  
dataset = {
  "a": [3, 3,    3,    3,    3],
  "b": [3, 3,    3,    3,    3],
  "c": [3, 3,    None, None, 3],
  "d": [3, 3,    3,    3,    1],
  "e": [3, None, 3,    3,    3],
}
```

Krippendorff's alpha ordinal or nominal in either of the cases, it returns 0. 

I don't know if this is an issue of Krippendorff's alpha algorithm itself or the problem with the implementation.

**Comment by o-P-o** [comment]
It's because in the implementation we're ending up with D_o = D_e = 1, and hence alpha = 0. According to the publication (linked below), this is the outcome when "observers agree as if chance had produced the result". I will have a further dig and see if the implementation is tripping up somewhere.

https://repository.upenn.edu/cgi/viewcontent.cgi?article=1043&context=asc_papers#:~:text=Krippendorff's%20alpha%20(%CE%B1)%20is%20a,assign%20computable%20values%20to%20them.

**Comment by o-P-o** [comment]
I worked through your example manually and I do indeed get an alpha value of zero. The implementation I used returns correct alpha values for a number of other examples so I'm curious as to what's going on here. I've emailed Krippendorff to see what he thinks. Maybe I'm doing something stupid.

**Comment by o-P-o** [comment]
I've confirmed from Krippendorff that the implementation is correct. This is his response:

"Your calculations are correct but your conception of reliability is not. Alpha measures whether the information in data can be trusted. Minimally, data needs to distinguish between whether or not something happened. Variation is essential. A while ago someone came with the same question but his problem was whether a medical test identified an illness. Two clinicians tested 1000 patients. Accordingly 998 didn’t have the illness. Regarding two patients, they disagreed on whether they were positive or negative. They wanted to conclude that the test was reliable with 99.8% agreement! The thing they and you overlooked is that data needs to distinguish something reliably. Reliability is an agreement on variations."
